##############################
#Deploying set-version .sh to agents
#Usage: ansible-playbook -u tooladm -i set_version_hosts --ask-pass deploy-set-version.yml
##############################

- hosts: all
  become: true 
  tasks:
  - name: copy sh file
    copy:
      src: /Users/afedotov/Work_local/jira-utils/setversion/setversion.sh
      dest: /buildtools/setversion/setversion.sh
      owner: builder
      group: builder
      mode: 0775